#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/53ced49b-72fc-498a-9669-e6a026b465b4 # 
title: add-user-api

/users:
  post:
    body: 
      application/json:
        example: 
          {"username": "tumama", "password": "fuemia", "email": "email@domain.com"}
    responses: 
      201:
        body: 
          application/json:
            example: 
              {"message": "your user was successfully created"}
      409:
        body: 
          application/json:
            example:
              userExists: 
                {"message": "the user name already exists"}
              emailExists: 
                {"message": "the email already exists"}

      400:
        body: 
          application/json:
            example:
              {"message": "the message is badly formed"}
      