#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/145dcebb-cc67-4f49-abc1-74c05e9ead25 # 
title: Register User API

/login:
  post:
    body: 
      application/json:
        example: 
          {"username": "tumama", "password": "fuemia"}
    responses: 
      200:
        body: 
          application/json:
            example: 
              {"message": "login succesfull"}
/users:
  post:
    body: 
      application/json:
        example: 
          {"username": "tumama", "password": "fuemia", "email": "email@domain.com"}
    responses: 
      201:
        body: 
          application/json:
            example: 
              {"message": "your user was successfully created"}
      409:
        body: 
          application/json:
            example:
              userExists: 
                {"message": "the user name already exists"}
              emailExists: 
                {"message": "the email already exists"}

      400:
        body: 
          application/json:
            example:
              {"message": "the message is badly formed"}
      